@host=http://localhost:3000/api

## Health Check
{{host}}

### Get Movies
GET {{host}}/movies

### Get a Movie
GET {{host}}/movies/1

###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email":"admin@example.com",
    "password":"secret"

}

### refresh token
GET {{host}}/auth/refresh
Cookie: __Host-refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDExNzU5NjIsImlhdCI6MTcwMTA4OTU2Miwic3ViIjoiMSJ9.643ga4UkM2GzlxuwsnLtLqo41Sn2cvTKLymSezzwupM


### logout

GET {{host}}/auth/logout


###
GET {{host}}/auth/me
Cookie: __Session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDEyNjUyNTcsImlhdCI6MTcwMTI2NDM1NywiaXNzIjoiZXhhbXBsZS5jb20iLCJuYW1lIjoiQWRtaW4gVXNlciIsInN1YiI6IjEiLCJ0eXAiOiJKV1QifQ.8UJ3upTHQS7hM7Z1qPVPaxANBRJRNjWwE1GM2KlKYRo