@host=http://localhost:8080/api

## Health Check
{{host}}

### Get Movies
GET {{host}}/movies

### Get a Movie
GET {{host}}/movies/1

###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email":"admin@example.com",
    "password":"secret"

}

### refresh token
GET {{host}}/auth/refresh
Cookie: __Session=""


### logout

GET {{host}}/auth/logout


###
GET {{host}}/auth/me
Cookie: __Session=""